### Examen 11/05/2026: Evaluación 3 Examen 2: Redes neuronales

<div style="border-style:groove;border-width:thin;padding:10px">
    <h4>NORMAS:</h4>
    <ul>
        <li>No se dispondrá de Internet durante el examen. Solo se podrán usar las presentaciones descargadas y una hoja escrita a mano por las dos caras.</li>
        <li>Queda prohibida cualquier comunicación entre vosotros o con el exterior.</li>
        <li>Deberá grabarse toda la sesión desde antes de recibir el examen hasta después de entregarlo utilizando OBS de forma local. La grabación se entregará a la vez que el examen. Quedan prohibidos los atajos de teclado del OBS</li> 
        <li>No se puede utilizar ninguna herramienta que asista a la programación. Ni basada en IA ni de otro tipo. Tampoco se podrá usar material hecho con IA, solo el material aportado por el profesor y el material hecho por el propio alumno (Sin IA).</li>
        <li>No se permite el uso de funciones genéricas que atajen distintos tipos de problemas. Solo se valorarán las soluciones concretas a lo que se pregunta. </li>
        <li>La entrega del examen se hará supervisada por el profesor y se anotará la hora exacta de entrega.</li>
        <li>Los móviles permanecerán durante toda la sesión sobre los PCs colocados con la pantalla hacia abajo.</li>
    </ul>
</div>

<div style="border-style:groove;border-width:thin;padding:10px">
    <h4>EJERCICIO 1:</h4>
    <p>Importa el dataset 'ai_workforce_displacement_global_2020_2026.csv'. Contiene datos sobre despidos por IA en los últimos 6 años por países y por sectores. Debes entrenar una IA para predecir la columna objetivo: net_workforce_change_pct. Trata de conseguir los siguientes objetivos:</p>
    <ol>
        <li>Adecúa los datos para poder solucionar el problema con IA.</li>
        <li>Resuelve el problema con una red neuronal usando todas las técnicas de deep learning que tengan sentido y siguiendo un proceso correcto para solucionar el problema. Debéis dejar TODAS LAS PRUEBAS QUE HAGÁIS. </li>
        <li>Haz una prueba de predicción futura. Predice el dato en España en el último trimestre de 2027. Valora si puede estar prediciendo bien con los datos que tienes.</li>
    </ol>
</div>

In [1]:
from os import listdir
from numpy import asarray
from numpy import save
import tensorflow as tf
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from tensorflow import keras
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVR
from sklearn.metrics import classification_report
import datetime
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv('destruccion_empleo.csv')

In [3]:
df.head()

,record_id,country,iso3_code,region,income_group,year,quarter,quarter_label,industry_sector,sector_automation_risk_score,gdp_per_capita_usd,pct_sector_workforce_displaced,data_source_notes
0,1,United States,USA,North America,High Income,2020,1,2020-Q1,Technology & Software,0.382,63514,0.0406,Research-calibrated synthetic data. Grounded i...
1,2,United States,USA,North America,High Income,2020,1,2020-Q1,Finance & Banking,0.608,63514,0.0517,Research-calibrated synthetic data. Grounded i...
2,3,United States,USA,North America,High Income,2020,1,2020-Q1,Healthcare & Life Sciences,0.198,63514,0.0176,Research-calibrated synthetic data. Grounded i...
3,4,United States,USA,North America,High Income,2020,1,2020-Q1,Manufacturing & Industry,0.720,63514,0.0924,Research-calibrated synthetic data. Grounded i...
4,5,United States,USA,North America,High Income,2020,1,2020-Q1,Retail & E-Commerce,0.676,63514,0.0667,Research-calibrated synthetic data. Grounded i...

In [4]:

df.drop(['record_id','country','data_source_notes','quarter_label' ],axis=1,inplace=True)
#1.2 Elegir las entradas.
#1. Borrar estas 4. record_id es un identificador, country es redundante por iso3_code y quarter_label es redundante con quarter y year.

In [5]:
df['income_group'].unique()
#Encaja el label encoding. Se evita el 0 porque a la hora de operar tiene un efecto distinto
df_solucion = df.replace({'High Income':4,'Upper Middle Income':3,'Lower Middle Income':2, 'Low Income':1})
#1.1 En este caso, income_group, puede ser label o puede ser one hot. El resto pueden ir con get_dummies.

C:\Users\Equipo\AppData\Local\Temp\ipykernel_19452\781610323.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_solucion = df.replace({'High Income':4,'Upper Middle Income':3,'Lower Middle Income':2, 'Low Income':1})

In [6]:
#Ya tenemos todo limpio, se puede hacer get_dummies
df_solucion = pd.get_dummies(df_solucion,dtype=int)

In [7]:
df_solucion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Columns: 108 entries, income_group to industry_sector_Transportation & Logistics
dtypes: float64(2), int64(106)
memory usage: 17.1 MB

In [8]:
y = df_solucion['pct_sector_workforce_displaced'].to_frame()
X = df_solucion.drop(['pct_sector_workforce_displaced'],axis=1)

In [9]:
df_solucion.corr()['pct_sector_workforce_displaced'].abs().sort_values(ascending=False)

pct_sector_workforce_displaced    1.000000
gdp_per_capita_usd                0.641091
income_group                      0.548548
sector_automation_risk_score      0.477408
year                              0.450259
                                    ...
iso3_code_HUN                     0.008761
quarter                           0.008421
iso3_code_POL                     0.007610
iso3_code_CHN                     0.004474
iso3_code_GRC                     0.003983
Name: pct_sector_workforce_displaced, Length: 108, dtype: float64

In [10]:
#Viendo la correlación anterior, debemos predecir que tenemos un problema. Seguramente no 
# llegaremos a tener un buen resultado. Vamos a escalar los datos. Escalo tanto X como y porque, de lo contario, 
# surge el problema de que no entrena.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
#y = scaler.fit_transform(y)

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [12]:
#Vamos a probar con un Decision Tree a ver que resultado da para marcar un límite inferior de lo que debemos conseguir:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor(random_state=42)
tree_reg.fit(X_train, y_train)
y_pred = tree_reg.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)
#1.3 Diseñado la red, el entrenamiento y comprobado buen resultado

0.9184200454893121

In [13]:
X.shape

(20800, 107)

In [ ]:
#1.4 Ha usado Técnicas de deep learning: batchnormalization, kernel_initializer y optimizers (al menos 3, si son 4 mejor)
#1.3 Diseñado la red, el entrenamiento y comprobado buen resultado 
model = keras.models.Sequential()
model.add(keras.layers.InputLayer(shape=X_train.shape[1:]))
model.add(keras.layers.Dense(64))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(16,activation='relu',kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(1,kernel_initializer='glorot_normal'))


model.compile(loss='mean_squared_error', optimizer = keras.optimizers.Adamax(learning_rate=0.00001, beta_1=0.9, beta_2=0.999), metrics=['mse'])

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10,
restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=100000,validation_split = 0.1,callbacks=[early_stopping_cb])

model.evaluate(X_test,y_test)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - loss: 1.2857 - mse: 1.2857 - val_loss: 1.2304 - val_mse: 1.2304
Epoch 2/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1.1293 - mse: 1.1293 - val_loss: 1.0680 - val_mse: 1.0680
Epoch 3/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.9788 - mse: 0.9788 - val_loss: 0.9253 - val_mse: 0.9253
Epoch 4/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.8605 - mse: 0.8605 - val_loss: 0.7901 - val_mse: 0.7901
Epoch 5/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 0.7526 - mse: 0.7526 - val_loss: 0.6922 - val_mse: 0.6922
Epoch 6/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.6623 - mse: 0.6623 - val_loss: 0.6023 - val_mse: 0.6023
Epoch 7/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.5841 - mse: 0.5841 - val_loss: 0.5216 - val_mse: 0.5216
Epoch 8/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.5134 - mse: 0.5134 - val_loss: 0.4556 - val_mse: 0.4556
Epoch 9/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4546 - mse: 0.4546 - val_loss: 0.3979 - val_mse: 0.3979
Epoch 10/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.4122 - mse: 0.4122 - val_loss: 0.3519 - val_mse: 0.3519
Epoch 11/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3655 - mse: 0.3655 - val_loss: 0.3118 - val_mse: 0.3118
Epoch 12/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3294 - mse: 0.3294 - val_loss: 0.2785 - val_mse: 0.2785
Epoch 13/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3002 - mse: 0.3002 - val_loss: 0.2517 - val_mse: 0.2517
Epoch 14/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.2799 - mse: 0.2799 - val_loss: 0.2229 - val_mse: 0.2229
Epoch 15/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.2538 - mse: 0.2538 - val_loss: 0.2050 - val_mse: 0.2050
Epoch 16/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2351 - mse: 0.2351 - val_loss: 0.1883 - val_mse: 0.1883
Epoch 17/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 0.2181 - mse: 0.2181 - val_loss: 0.1706 - val_mse: 0.1706
Epoch 18/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2003 - mse: 0.2003 - val_loss: 0.1571 - val_mse: 0.1571
Epoch 19/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.1937 - mse: 0.1937 - val_loss: 0.1464 - val_mse: 0.1464
Epoch 20/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.1819 - mse: 0.1819 - val_loss: 0.1352 - val_mse: 0.1352
Epoch 21/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 0.1679 - mse: 0.1679 - val_loss: 0.1229 - val_mse: 0.1229
Epoch 22/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.1594 - mse: 0.1594 - val_loss: 0.1166 - val_mse: 0.1166
Epoch 23/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 0.1500 - mse: 0.1500 - val_loss: 0.1104 - val_mse: 0.1104
Epoch 24/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.1431 - mse: 0.1431 - val_loss: 0.1043 - val_mse: 0.1043
Epoch 25/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.1357 - mse: 0.1357 - val_loss: 0.0968 - val_mse: 0.0968
Epoch 26/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1305 - mse: 0.1305 - val_loss: 0.0919 - val_mse: 0.0919
Epoch 27/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1248 - mse: 0.1248 - val_loss: 0.0871 - val_mse: 0.0871
Epoch 28/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1204 - mse: 0.1204 - val_loss: 0.0811 - val_mse: 0.0811
Epoch 29/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1157 - mse: 0.1157 - val_loss: 0.0796 - val_mse: 0.0796
Epoch 30/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1127 - mse: 0.1127 - val_loss: 0.0744 - val_mse: 0.0744
Epoch 31/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1094 - mse: 0.1094 - val_loss: 0.0711 - val_mse: 0.0711
Epoch 32/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1043 - mse: 0.1043 - val_loss: 0.0690 - val_mse: 0.0690
Epoch 33/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0990 - mse: 0.0990 - val_loss: 0.0666 - val_mse: 0.0666
Epoch 34/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0975 - mse: 0.0975 - val_loss: 0.0630 - val_mse: 0.0630
Epoch 35/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0950 - mse: 0.0950 - val_loss: 0.0601 - val_mse: 0.0601
Epoch 36/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0921 - mse: 0.0921 - val_loss: 0.0572 - val_mse: 0.0572
Epoch 37/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0899 - mse: 0.0899 - val_loss: 0.0552 - val_mse: 0.0552
Epoch 38/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0859 - mse: 0.0859 - val_loss: 0.0538 - val_mse: 0.0538
Epoch 39/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0856 - mse: 0.0856 - val_loss: 0.0506 - val_mse: 0.0506
Epoch 40/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0825 - mse: 0.0825 - val_loss: 0.0490 - val_mse: 0.0490
Epoch 41/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0805 - mse: 0.0805 - val_loss: 0.0480 - val_mse: 0.0480
Epoch 42/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0792 - mse: 0.0792 - val_loss: 0.0454 - val_mse: 0.0454
Epoch 43/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0782 - mse: 0.0782 - val_loss: 0.0449 - val_mse: 0.0449
Epoch 44/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0757 - mse: 0.0757 - val_loss: 0.0427 - val_mse: 0.0427
Epoch 45/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0719 - mse: 0.0719 - val_loss: 0.0412 - val_mse: 0.0412
Epoch 46/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0703 - mse: 0.0703 - val_loss: 0.0397 - val_mse: 0.0397
Epoch 47/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0703 - mse: 0.0703 - val_loss: 0.0392 - val_mse: 0.0392
Epoch 48/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0703 - mse: 0.0703 - val_loss: 0.0373 - val_mse: 0.0373
Epoch 49/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0686 - mse: 0.0686 - val_loss: 0.0372 - val_mse: 0.0372
Epoch 50/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0655 - mse: 0.0655 - val_loss: 0.0355 - val_mse: 0.0355
Epoch 51/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0647 - mse: 0.0647 - val_loss: 0.0342 - val_mse: 0.0342
Epoch 52/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0637 - mse: 0.0637 - val_loss: 0.0334 - val_mse: 0.0334
Epoch 53/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.0608 - mse: 0.0608 - val_loss: 0.0322 - val_mse: 0.0322
Epoch 54/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.0612 - mse: 0.0612 - val_loss: 0.0314 - val_mse: 0.0314
Epoch 55/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0588 - mse: 0.0588 - val_loss: 0.0307 - val_mse: 0.0307
Epoch 56/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0587 - mse: 0.0587 - val_loss: 0.0293 - val_mse: 0.0293
Epoch 57/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0583 - mse: 0.0583 - val_loss: 0.0291 - val_mse: 0.0291
Epoch 58/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0565 - mse: 0.0565 - val_loss: 0.0278 - val_mse: 0.0278
Epoch 59/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0551 - mse: 0.0551 - val_loss: 0.0268 - val_mse: 0.0268
Epoch 60/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0544 - mse: 0.0544 - val_loss: 0.0272 - val_mse: 0.0272
Epoch 61/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0536 - mse: 0.0536 - val_loss: 0.0252 - val_mse: 0.0252
Epoch 62/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0529 - mse: 0.0529 - val_loss: 0.0251 - val_mse: 0.0251
Epoch 63/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0505 - mse: 0.0505 - val_loss: 0.0244 - val_mse: 0.0244
Epoch 64/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0503 - mse: 0.0503 - val_loss: 0.0234 - val_mse: 0.0234
Epoch 65/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0494 - mse: 0.0494 - val_loss: 0.0232 - val_mse: 0.0232
Epoch 66/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0476 - mse: 0.0476 - val_loss: 0.0226 - val_mse: 0.0226
Epoch 67/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0483 - mse: 0.0483 - val_loss: 0.0226 - val_mse: 0.0226
Epoch 68/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0456 - mse: 0.0456 - val_loss: 0.0212 - val_mse: 0.0212
Epoch 69/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0470 - mse: 0.0470 - val_loss: 0.0211 - val_mse: 0.0211
Epoch 70/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0459 - mse: 0.0459 - val_loss: 0.0212 - val_mse: 0.0212
Epoch 71/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0457 - mse: 0.0457 - val_loss: 0.0207 - val_mse: 0.0207
Epoch 72/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0440 - mse: 0.0440 - val_loss: 0.0199 - val_mse: 0.0199
Epoch 73/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0428 - mse: 0.0428 - val_loss: 0.0190 - val_mse: 0.0190
Epoch 74/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0424 - mse: 0.0424 - val_loss: 0.0185 - val_mse: 0.0185
Epoch 75/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.0408 - mse: 0.0408 - val_loss: 0.0187 - val_mse: 0.0187
Epoch 76/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 0.0417 - mse: 0.0417 - val_loss: 0.0180 - val_mse: 0.0180
Epoch 77/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 0.0396 - mse: 0.0396 - val_loss: 0.0169 - val_mse: 0.0169
Epoch 78/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0401 - mse: 0.0401 - val_loss: 0.0169 - val_mse: 0.0169
Epoch 79/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0393 - mse: 0.0393 - val_loss: 0.0168 - val_mse: 0.0168
Epoch 80/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0381 - mse: 0.0381 - val_loss: 0.0160 - val_mse: 0.0160
Epoch 81/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0381 - mse: 0.0381 - val_loss: 0.0161 - val_mse: 0.0161
Epoch 82/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0377 - mse: 0.0377 - val_loss: 0.0157 - val_mse: 0.0157
Epoch 83/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 0.0364 - mse: 0.0364 - val_loss: 0.0153 - val_mse: 0.0153
Epoch 84/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0376 - mse: 0.0376 - val_loss: 0.0150 - val_mse: 0.0150
Epoch 85/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0358 - mse: 0.0358 - val_loss: 0.0145 - val_mse: 0.0145
Epoch 86/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0357 - mse: 0.0357 - val_loss: 0.0139 - val_mse: 0.0139
Epoch 87/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0342 - mse: 0.0342 - val_loss: 0.0140 - val_mse: 0.0140
Epoch 88/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0331 - mse: 0.0331 - val_loss: 0.0135 - val_mse: 0.0135
Epoch 89/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0339 - mse: 0.0339 - val_loss: 0.0131 - val_mse: 0.0131
Epoch 90/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 0.0328 - mse: 0.0328 - val_loss: 0.0131 - val_mse: 0.0131
Epoch 91/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0320 - mse: 0.0320 - val_loss: 0.0127 - val_mse: 0.0127
Epoch 92/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0319 - mse: 0.0319 - val_loss: 0.0124 - val_mse: 0.0124
Epoch 93/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 0.0323 - mse: 0.0323 - val_loss: 0.0122 - val_mse: 0.0122
Epoch 94/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 0.0305 - mse: 0.0305 - val_loss: 0.0117 - val_mse: 0.0117
Epoch 95/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0304 - mse: 0.0304 - val_loss: 0.0117 - val_mse: 0.0117
Epoch 96/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.0297 - mse: 0.0297 - val_loss: 0.0114 - val_mse: 0.0114
Epoch 97/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 0.0296 - mse: 0.0296 - val_loss: 0.0114 - val_mse: 0.0114
Epoch 98/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 0.0301 - mse: 0.0301 - val_loss: 0.0111 - val_mse: 0.0111
Epoch 99/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.0286 - mse: 0.0286 - val_loss: 0.0106 - val_mse: 0.0106
Epoch 100/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 0.0284 - mse: 0.0284 - val_loss: 0.0105 - val_mse: 0.0105
Epoch 101/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0282 - mse: 0.0282 - val_loss: 0.0105 - val_mse: 0.0105
Epoch 102/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0278 - mse: 0.0278 - val_loss: 0.0104 - val_mse: 0.0104
Epoch 103/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.0281 - mse: 0.0281 - val_loss: 0.0100 - val_mse: 0.0100
Epoch 104/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 0.0270 - mse: 0.0270 - val_loss: 0.0097 - val_mse: 0.0097
Epoch 105/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 0.0266 - mse: 0.0266 - val_loss: 0.0097 - val_mse: 0.0097
Epoch 106/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0265 - mse: 0.0265 - val_loss: 0.0096 - val_mse: 0.0096
Epoch 107/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0257 - mse: 0.0257 - val_loss: 0.0091 - val_mse: 0.0091
Epoch 108/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0253 - mse: 0.0253 - val_loss: 0.0092 - val_mse: 0.0092
Epoch 109/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0255 - mse: 0.0255 - val_loss: 0.0089 - val_mse: 0.0089
Epoch 110/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0249 - mse: 0.0249 - val_loss: 0.0088 - val_mse: 0.0088
Epoch 111/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0244 - mse: 0.0244 - val_loss: 0.0083 - val_mse: 0.0083
Epoch 112/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0241 - mse: 0.0241 - val_loss: 0.0085 - val_mse: 0.0085
Epoch 113/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0241 - mse: 0.0241 - val_loss: 0.0080 - val_mse: 0.0080
Epoch 114/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0233 - mse: 0.0233 - val_loss: 0.0082 - val_mse: 0.0082
Epoch 115/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0228 - mse: 0.0228 - val_loss: 0.0078 - val_mse: 0.0078
Epoch 116/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0234 - mse: 0.0234 - val_loss: 0.0077 - val_mse: 0.0077
Epoch 117/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0224 - mse: 0.0224 - val_loss: 0.0075 - val_mse: 0.0075
Epoch 118/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0222 - mse: 0.0222 - val_loss: 0.0073 - val_mse: 0.0073
Epoch 119/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0225 - mse: 0.0225 - val_loss: 0.0074 - val_mse: 0.0074
Epoch 120/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0215 - mse: 0.0215 - val_loss: 0.0072 - val_mse: 0.0072
Epoch 121/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0215 - mse: 0.0215 - val_loss: 0.0072 - val_mse: 0.0072
Epoch 122/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0213 - mse: 0.0213 - val_loss: 0.0070 - val_mse: 0.0070
Epoch 123/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0208 - mse: 0.0208 - val_loss: 0.0071 - val_mse: 0.0071
Epoch 124/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0206 - mse: 0.0206 - val_loss: 0.0069 - val_mse: 0.0069
Epoch 125/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0204 - mse: 0.0204 - val_loss: 0.0068 - val_mse: 0.0068
Epoch 126/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0203 - mse: 0.0203 - val_loss: 0.0066 - val_mse: 0.0066
Epoch 127/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0200 - mse: 0.0200 - val_loss: 0.0065 - val_mse: 0.0065
Epoch 128/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0203 - mse: 0.0203 - val_loss: 0.0065 - val_mse: 0.0065
Epoch 129/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0197 - mse: 0.0197 - val_loss: 0.0064 - val_mse: 0.0064
Epoch 130/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0199 - mse: 0.0199 - val_loss: 0.0062 - val_mse: 0.0062
Epoch 131/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0183 - mse: 0.0183 - val_loss: 0.0060 - val_mse: 0.0060
Epoch 132/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0188 - mse: 0.0188 - val_loss: 0.0059 - val_mse: 0.0059
Epoch 133/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0189 - mse: 0.0189 - val_loss: 0.0059 - val_mse: 0.0059
Epoch 134/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0188 - mse: 0.0188 - val_loss: 0.0058 - val_mse: 0.0058
Epoch 135/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0179 - mse: 0.0179 - val_loss: 0.0059 - val_mse: 0.0059
Epoch 136/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0181 - mse: 0.0181 - val_loss: 0.0057 - val_mse: 0.0057
Epoch 137/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0179 - mse: 0.0179 - val_loss: 0.0059 - val_mse: 0.0059
Epoch 138/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0181 - mse: 0.0181 - val_loss: 0.0054 - val_mse: 0.0054
Epoch 139/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0171 - mse: 0.0171 - val_loss: 0.0052 - val_mse: 0.0052
Epoch 140/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0172 - mse: 0.0172 - val_loss: 0.0054 - val_mse: 0.0054
Epoch 141/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0168 - mse: 0.0168 - val_loss: 0.0052 - val_mse: 0.0052
Epoch 142/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0170 - mse: 0.0170 - val_loss: 0.0051 - val_mse: 0.0051
Epoch 143/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 0.0169 - mse: 0.0169 - val_loss: 0.0049 - val_mse: 0.0049
Epoch 144/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0160 - mse: 0.0160 - val_loss: 0.0050 - val_mse: 0.0050
Epoch 145/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0163 - mse: 0.0163 - val_loss: 0.0049 - val_mse: 0.0049
Epoch 146/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0161 - mse: 0.0161 - val_loss: 0.0048 - val_mse: 0.0048
Epoch 147/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0158 - mse: 0.0158 - val_loss: 0.0046 - val_mse: 0.0046
Epoch 148/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 0.0161 - mse: 0.0161 - val_loss: 0.0047 - val_mse: 0.0047
Epoch 149/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.0156 - mse: 0.0156 - val_loss: 0.0047 - val_mse: 0.0047
Epoch 150/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0152 - mse: 0.0152 - val_loss: 0.0045 - val_mse: 0.0045
Epoch 151/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0149 - mse: 0.0149 - val_loss: 0.0043 - val_mse: 0.0043
Epoch 152/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0148 - mse: 0.0148 - val_loss: 0.0043 - val_mse: 0.0043
Epoch 153/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0151 - mse: 0.0151 - val_loss: 0.0043 - val_mse: 0.0043
Epoch 154/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0142 - mse: 0.0142 - val_loss: 0.0042 - val_mse: 0.0042
Epoch 155/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0148 - mse: 0.0148 - val_loss: 0.0043 - val_mse: 0.0043
Epoch 156/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0145 - mse: 0.0145 - val_loss: 0.0042 - val_mse: 0.0042
Epoch 157/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0140 - mse: 0.0140 - val_loss: 0.0041 - val_mse: 0.0041
Epoch 158/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0141 - mse: 0.0141 - val_loss: 0.0040 - val_mse: 0.0040
Epoch 159/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0141 - mse: 0.0141 - val_loss: 0.0040 - val_mse: 0.0040
Epoch 160/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0141 - mse: 0.0141 - val_loss: 0.0041 - val_mse: 0.0041
Epoch 161/100000

[0.0003683316463138908, 0.0003683316463138908]

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.InputLayer(shape=X_train.shape[1:]))
model.add(keras.layers.Dense(64))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(16,activation='relu',kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(1,kernel_initializer='glorot_normal'))


model.compile(loss='mean_squared_error', optimizer = keras.optimizers.RMSprop(learning_rate=0.001, rho=0.9), metrics=['mse'])

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10,restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=100000,validation_split = 0.1,callbacks=[early_stopping_cb])

model.evaluate(X_test,y_test)

Epoch 1/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.0409 - mse: 0.0409 - val_loss: 9.7178e-04 - val_mse: 9.7178e-04
Epoch 2/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0011 - mse: 0.0011 - val_loss: 5.0697e-04 - val_mse: 5.0697e-04
Epoch 3/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2752e-04 - mse: 6.2752e-04 - val_loss: 2.0579e-04 - val_mse: 2.0579e-04
Epoch 4/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4.4257e-04 - mse: 4.4257e-04 - val_loss: 2.0486e-04 - val_mse: 2.0486e-04
Epoch 5/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3.8833e-04 - mse: 3.8833e-04 - val_loss: 2.8484e-04 - val_mse: 2.8484e-04
Epoch 6/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.5269e-04 - mse: 3.5269e-04 - val_loss: 2.0177e-04 - val_mse: 2.0177e-04
Epoch 7/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.1871e-04 - mse: 3.1871e-04 - val_loss: 2.5470e-04 - val_mse: 2.5470e-04
Epoch 8/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.0740e-04 - mse: 3.0740e-04 - val_loss: 1.4943e-04 - val_mse: 1.4943e-04
Epoch 9/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.2051e-04 - mse: 3.2051e-04 - val_loss: 2.0769e-04 - val_mse: 2.0769e-04
Epoch 10/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.1256e-04 - mse: 3.1256e-04 - val_loss: 3.8806e-04 - val_mse: 3.8806e-04
Epoch 11/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.8947e-04 - mse: 2.8947e-04 - val_loss: 2.3083e-04 - val_mse: 2.3083e-04
Epoch 12/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.1545e-04 - mse: 3.1545e-04 - val_loss: 1.7570e-04 - val_mse: 1.7570e-04
Epoch 13/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.6632e-04 - mse: 2.6632e-04 - val_loss: 1.6514e-04 - val_mse: 1.6514e-04
Epoch 14/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.9014e-04 - mse: 2.9014e-04 - val_loss: 1.3687e-04 - val_mse: 1.3687e-04
Epoch 15/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.5189e-04 - mse: 2.5189e-04 - val_loss: 1.4160e-04 - val_mse: 1.4160e-04
Epoch 16/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.7419e-04 - mse: 2.7419e-04 - val_loss: 3.5252e-04 - val_mse: 3.5252e-04
Epoch 17/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.6667e-04 - mse: 2.6667e-04 - val_loss: 3.4639e-04 - val_mse: 3.4639e-04
Epoch 18/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.4602e-04 - mse: 2.4602e-04 - val_loss: 4.3654e-04 - val_mse: 4.3654e-04
Epoch 19/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.5713e-04 - mse: 2.5713e-04 - val_loss: 1.1767e-04 - val_mse: 1.1767e-04
Epoch 20/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.5453e-04 - mse: 2.5453e-04 - val_loss: 4.0139e-04 - val_mse: 4.0139e-04
Epoch 21/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.4364e-04 - mse: 2.4364e-04 - val_loss: 1.1245e-04 - val_mse: 1.1245e-04
Epoch 22/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.4771e-04 - mse: 2.4771e-04 - val_loss: 2.3944e-04 - val_mse: 2.3944e-04
Epoch 23/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.4314e-04 - mse: 2.4314e-04 - val_loss: 1.1453e-04 - val_mse: 1.1453e-04
Epoch 24/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2919e-04 - mse: 2.2919e-04 - val_loss: 3.2169e-04 - val_mse: 3.2169e-04
Epoch 25/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3954e-04 - mse: 2.3954e-04 - val_loss: 2.3804e-04 - val_mse: 2.3804e-04
Epoch 26/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3468e-04 - mse: 2.3468e-04 - val_loss: 1.5418e-04 - val_mse: 1.5418e-04
Epoch 27/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2751e-04 - mse: 2.2751e-04 - val_loss: 1.0161e-04 - val_mse: 1.0161e-04
Epoch 28/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3348e-04 - mse: 2.3348e-04 - val_loss: 1.7799e-04 - val_mse: 1.7799e-04
Epoch 29/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.5250e-04 - mse: 2.5250e-04 - val_loss: 2.2482e-04 - val_mse: 2.2482e-04
Epoch 30/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.4631e-04 - mse: 2.4631e-04 - val_loss: 9.8691e-05 - val_mse: 9.8691e-05
Epoch 31/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3749e-04 - mse: 2.3749e-04 - val_loss: 1.5439e-04 - val_mse: 1.5439e-04
Epoch 32/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 2.4082e-04 - mse: 2.4082e-04 - val_loss: 1.9627e-04 - val_mse: 1.9627e-04
Epoch 33/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.4120e-04 - mse: 2.4120e-04 - val_loss: 1.8499e-04 - val_mse: 1.8499e-04
Epoch 34/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2660e-04 - mse: 2.2660e-04 - val_loss: 1.1662e-04 - val_mse: 1.1662e-04
Epoch 35/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.1247e-04 - mse: 2.1247e-04 - val_loss: 9.8857e-05 - val_mse: 9.8857e-05
Epoch 36/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.4448e-04 - mse: 2.4448e-04 - val_loss: 2.4841e-04 - val_mse: 2.4841e-04
Epoch 37/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.5053e-04 - mse: 2.5053e-04 - val_loss: 1.2650e-04 - val_mse: 1.2650e-04
Epoch 38/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.1970e-04 - mse: 2.1970e-04 - val_loss: 9.3386e-05 - val_mse: 9.3386e-05
Epoch 39/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3706e-04 - mse: 2.3706e-04 - val_loss: 1.2102e-04 - val_mse: 1.2102e-04
Epoch 40/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2559e-04 - mse: 2.2559e-04 - val_loss: 8.8345e-05 - val_mse: 8.8345e-05
Epoch 41/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3236e-04 - mse: 2.3236e-04 - val_loss: 1.7524e-04 - val_mse: 1.7524e-04
Epoch 42/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.5956e-04 - mse: 2.5956e-04 - val_loss: 1.6518e-04 - val_mse: 1.6518e-04
Epoch 43/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3488e-04 - mse: 2.3488e-04 - val_loss: 1.2536e-04 - val_mse: 1.2536e-04
Epoch 44/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.1721e-04 - mse: 2.1721e-04 - val_loss: 1.9400e-04 - val_mse: 1.9400e-04
Epoch 45/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.0495e-04 - mse: 2.0495e-04 - val_loss: 1.0013e-04 - val_mse: 1.0013e-04
Epoch 46/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2569e-04 - mse: 2.2569e-04 - val_loss: 1.8778e-04 - val_mse: 1.8778e-04
Epoch 47/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2592e-04 - mse: 2.2592e-04 - val_loss: 1.0914e-04 - val_mse: 1.0914e-04
Epoch 48/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3722e-04 - mse: 2.3722e-04 - val_loss: 1.1515e-04 - val_mse: 1.1515e-04
Epoch 49/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.0707e-04 - mse: 2.0707e-04 - val_loss: 8.7099e-05 - val_mse: 8.7099e-05
Epoch 50/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2558e-04 - mse: 2.2558e-04 - val_loss: 9.6097e-05 - val_mse: 9.6097e-05
Epoch 51/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.1034e-04 - mse: 2.1034e-04 - val_loss: 1.7266e-04 - val_mse: 1.7266e-04
Epoch 52/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2723e-04 - mse: 2.2723e-04 - val_loss: 9.4471e-05 - val_mse: 9.4471e-05
Epoch 53/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.1288e-04 - mse: 2.1288e-04 - val_loss: 1.8791e-04 - val_mse: 1.8791e-04
Epoch 54/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.0648e-04 - mse: 2.0648e-04 - val_loss: 8.3999e-05 - val_mse: 8.3999e-05
Epoch 55/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2468e-04 - mse: 2.2468e-04 - val_loss: 1.2757e-04 - val_mse: 1.2757e-04
Epoch 56/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2351e-04 - mse: 2.2351e-04 - val_loss: 9.8698e-05 - val_mse: 9.8698e-05
Epoch 57/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.1814e-04 - mse: 2.1814e-04 - val_loss: 1.1779e-04 - val_mse: 1.1779e-04
Epoch 58/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3111e-04 - mse: 2.3111e-04 - val_loss: 1.5443e-04 - val_mse: 1.5443e-04
Epoch 59/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2588e-04 - mse: 2.2588e-04 - val_loss: 9.8272e-05 - val_mse: 9.8272e-05
Epoch 60/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2.3553e-04 - mse: 2.3553e-04 - val_loss: 1.1139e-04 - val_mse: 1.1139e-04
Epoch 61/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2490e-04 - mse: 2.2490e-04 - val_loss: 2.3932e-04 - val_mse: 2.3932e-04
Epoch 62/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2646e-04 - mse: 2.2646e-04 - val_loss: 1.0342e-04 - val_mse: 1.0342e-04
Epoch 63/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2425e-04 - mse: 2.2425e-04 - val_loss: 1.0466e-04 - val_mse: 1.0466e-04
Epoch 64/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.0147e-04 - mse: 2.0147e-04 - val_loss: 1.0352e-04 - val_mse: 1.0352e-04
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3089e-05 - mse: 8.3089e-05

[8.308862015837803e-05, 8.308862015837803e-05]

In [15]:
y_pred = model.predict(X_test)
r2_score(y_test,y_pred)

65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

0.8047083616256714

In [13]:
model = keras.models.Sequential()
model.add(keras.layers.InputLayer(shape=X_train.shape[1:]))
model.add(keras.layers.Dense(64))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(16,activation='relu',kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(1,kernel_initializer='glorot_normal'))


model.compile(loss='mean_squared_error', optimizer = keras.optimizers.Nadam(learning_rate=0.001, beta_1=0.9, beta_2=0.999), metrics=['mse'])

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10,restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=100000,validation_split = 0.1,callbacks=[early_stopping_cb])

model.evaluate(X_test,y_test)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0911 - mse: 0.0911 - val_loss: 0.0051 - val_mse: 0.0051
Epoch 2/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0086 - mse: 0.0086 - val_loss: 0.0018 - val_mse: 0.0018
Epoch 3/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0040 - mse: 0.0040 - val_loss: 7.1842e-04 - val_mse: 7.1842e-04
Epoch 4/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0024 - mse: 0.0024 - val_loss: 6.7880e-04 - val_mse: 6.7880e-04
Epoch 5/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0016 - mse: 0.0016 - val_loss: 4.7838e-04 - val_mse: 4.7838e-04
Epoch 6/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0012 - mse: 0.0012 - val_loss: 4.5336e-04 - val_mse: 4.5336e-04
Epoch 7/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3117e-04 - mse: 9.3117e-04 - val_loss: 3.6844e-04 - val_mse: 3.6844e-04
Epoch 8/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.4373e-04 - mse: 7.4373e-04 - val_loss: 2.8751e-04 - val_mse: 2.8751e-04
Epoch 9/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1752e-04 - mse: 6.1752e-04 - val_loss: 3.2386e-04 - val_mse: 3.2386e-04
Epoch 10/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5.0612e-04 - mse: 5.0612e-04 - val_loss: 2.5701e-04 - val_mse: 2.5701e-04
Epoch 11/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4.6873e-04 - mse: 4.6873e-04 - val_loss: 2.5354e-04 - val_mse: 2.5354e-04
Epoch 12/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4.0320e-04 - mse: 4.0320e-04 - val_loss: 1.8942e-04 - val_mse: 1.8942e-04
Epoch 13/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.5935e-04 - mse: 3.5935e-04 - val_loss: 1.7452e-04 - val_mse: 1.7452e-04
Epoch 14/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.2694e-04 - mse: 3.2694e-04 - val_loss: 1.6795e-04 - val_mse: 1.6795e-04
Epoch 15/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.0799e-04 - mse: 3.0799e-04 - val_loss: 1.7668e-04 - val_mse: 1.7668e-04
Epoch 16/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.8750e-04 - mse: 2.8750e-04 - val_loss: 1.3566e-04 - val_mse: 1.3566e-04
Epoch 17/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.8189e-04 - mse: 2.8189e-04 - val_loss: 1.4268e-04 - val_mse: 1.4268e-04
Epoch 18/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.5524e-04 - mse: 2.5524e-04 - val_loss: 1.5462e-04 - val_mse: 1.5462e-04
Epoch 19/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.4514e-04 - mse: 2.4514e-04 - val_loss: 1.6929e-04 - val_mse: 1.6929e-04
Epoch 20/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2262e-04 - mse: 2.2262e-04 - val_loss: 1.1532e-04 - val_mse: 1.1532e-04
Epoch 21/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2520e-04 - mse: 2.2520e-04 - val_loss: 1.0640e-04 - val_mse: 1.0640e-04
Epoch 22/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.1849e-04 - mse: 2.1849e-04 - val_loss: 1.1770e-04 - val_mse: 1.1770e-04
Epoch 23/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.2134e-04 - mse: 2.2134e-04 - val_loss: 1.1484e-04 - val_mse: 1.1484e-04
Epoch 24/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.1168e-04 - mse: 2.1168e-04 - val_loss: 2.0553e-04 - val_mse: 2.0553e-04
Epoch 25/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.0971e-04 - mse: 2.0971e-04 - val_loss: 1.0462e-04 - val_mse: 1.0462e-04
Epoch 26/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.0088e-04 - mse: 2.0088e-04 - val_loss: 1.4434e-04 - val_mse: 1.4434e-04
Epoch 27/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.9885e-04 - mse: 1.9885e-04 - val_loss: 1.1287e-04 - val_mse: 1.1287e-04
Epoch 28/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.8684e-04 - mse: 1.8684e-04 - val_loss: 1.3420e-04 - val_mse: 1.3420e-04
Epoch 29/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.9509e-04 - mse: 1.9509e-04 - val_loss: 1.7147e-04 - val_mse: 1.7147e-04
Epoch 30/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.8818e-04 - mse: 1.8818e-04 - val_loss: 1.3097e-04 - val_mse: 1.3097e-04
Epoch 31/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.8680e-04 - mse: 1.8680e-04 - val_loss: 1.3641e-04 - val_mse: 1.3641e-04
Epoch 32/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.9301e-04 - mse: 1.9301e-04 - val_loss: 9.6450e-05 - val_mse: 9.6450e-05
Epoch 33/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.8319e-04 - mse: 1.8319e-04 - val_loss: 8.8091e-05 - val_mse: 8.8091e-05
Epoch 34/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7810e-04 - mse: 1.7810e-04 - val_loss: 1.0348e-04 - val_mse: 1.0348e-04
Epoch 35/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7822e-04 - mse: 1.7822e-04 - val_loss: 8.6496e-05 - val_mse: 8.6496e-05
Epoch 36/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7256e-04 - mse: 1.7256e-04 - val_loss: 8.4204e-05 - val_mse: 8.4204e-05
Epoch 37/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.6698e-04 - mse: 1.6698e-04 - val_loss: 1.0443e-04 - val_mse: 1.0443e-04
Epoch 38/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7647e-04 - mse: 1.7647e-04 - val_loss: 8.3538e-05 - val_mse: 8.3538e-05
Epoch 39/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.7249e-04 - mse: 1.7249e-04 - val_loss: 1.1811e-04 - val_mse: 1.1811e-04
Epoch 40/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7910e-04 - mse: 1.7910e-04 - val_loss: 9.5391e-05 - val_mse: 9.5391e-05
Epoch 41/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.7752e-04 - mse: 1.7752e-04 - val_loss: 1.1702e-04 - val_mse: 1.1702e-04
Epoch 42/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7337e-04 - mse: 1.7337e-04 - val_loss: 1.1981e-04 - val_mse: 1.1981e-04
Epoch 43/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.6494e-04 - mse: 1.6494e-04 - val_loss: 1.0419e-04 - val_mse: 1.0419e-04
Epoch 44/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.7467e-04 - mse: 1.7467e-04 - val_loss: 1.1267e-04 - val_mse: 1.1267e-04
Epoch 45/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.7242e-04 - mse: 1.7242e-04 - val_loss: 9.2084e-05 - val_mse: 9.2084e-05
Epoch 46/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7487e-04 - mse: 1.7487e-04 - val_loss: 9.4122e-05 - val_mse: 9.4122e-05
Epoch 47/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7551e-04 - mse: 1.7551e-04 - val_loss: 8.9342e-05 - val_mse: 8.9342e-05
Epoch 48/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.5299e-04 - mse: 1.5299e-04 - val_loss: 8.8131e-05 - val_mse: 8.8131e-05
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.9317e-05 - mse: 8.9317e-05

[8.931724732974544e-05, 8.931724732974544e-05]

In [14]:
y_pred = model.predict(X_test)
r2_score(y_test,y_pred)

65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step

0.9526434540748596

In [16]:
model = keras.models.Sequential()
model.add(keras.layers.InputLayer(shape=X_train.shape[1:]))
model.add(keras.layers.Dense(64))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(16,activation='relu',kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(1,kernel_initializer='glorot_normal'))


model.compile(loss='mean_squared_error', optimizer = keras.optimizers.Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999), metrics=['mse'])

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10,
restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=100000,validation_split = 0.1,callbacks=[early_stopping_cb])

model.evaluate(X_test,y_test)

Epoch 1/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.0198 - mse: 0.0198 - val_loss: 4.3172e-04 - val_mse: 4.3172e-04
Epoch 2/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.0067e-04 - mse: 7.0067e-04 - val_loss: 3.2583e-04 - val_mse: 3.2583e-04
Epoch 3/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.4120e-04 - mse: 5.4120e-04 - val_loss: 3.8631e-04 - val_mse: 3.8631e-04
Epoch 4/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5.0322e-04 - mse: 5.0322e-04 - val_loss: 3.5731e-04 - val_mse: 3.5731e-04
Epoch 5/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 4.2911e-04 - mse: 4.2911e-04 - val_loss: 3.2098e-04 - val_mse: 3.2098e-04
Epoch 6/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.7725e-04 - mse: 3.7725e-04 - val_loss: 2.2057e-04 - val_mse: 2.2057e-04
Epoch 7/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.1774e-04 - mse: 3.1774e-04 - val_loss: 1.5451e-04 - val_mse: 1.5451e-04
Epoch 8/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.8911e-04 - mse: 2.8911e-04 - val_loss: 1.7487e-04 - val_mse: 1.7487e-04
Epoch 9/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.7971e-04 - mse: 2.7971e-04 - val_loss: 1.4013e-04 - val_mse: 1.4013e-04
Epoch 10/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.7820e-04 - mse: 2.7820e-04 - val_loss: 1.9081e-04 - val_mse: 1.9081e-04
Epoch 11/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2.8059e-04 - mse: 2.8059e-04 - val_loss: 1.6566e-04 - val_mse: 1.6566e-04
Epoch 12/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.7305e-04 - mse: 2.7305e-04 - val_loss: 1.3013e-04 - val_mse: 1.3013e-04
Epoch 13/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 2.5822e-04 - mse: 2.5822e-04 - val_loss: 2.7467e-04 - val_mse: 2.7467e-04
Epoch 14/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 2.4678e-04 - mse: 2.4678e-04 - val_loss: 1.1203e-04 - val_mse: 1.1203e-04
Epoch 15/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.5068e-04 - mse: 2.5068e-04 - val_loss: 2.3899e-04 - val_mse: 2.3899e-04
Epoch 16/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.6601e-04 - mse: 2.6601e-04 - val_loss: 1.1413e-04 - val_mse: 1.1413e-04
Epoch 17/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 2.2830e-04 - mse: 2.2830e-04 - val_loss: 1.3905e-04 - val_mse: 1.3905e-04
Epoch 18/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2.3234e-04 - mse: 2.3234e-04 - val_loss: 1.1465e-04 - val_mse: 1.1465e-04
Epoch 19/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.3329e-04 - mse: 2.3329e-04 - val_loss: 1.0306e-04 - val_mse: 1.0306e-04
Epoch 20/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 2.4330e-04 - mse: 2.4330e-04 - val_loss: 1.5569e-04 - val_mse: 1.5569e-04
Epoch 21/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2.5452e-04 - mse: 2.5452e-04 - val_loss: 1.1315e-04 - val_mse: 1.1315e-04
Epoch 22/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 2.4067e-04 - mse: 2.4067e-04 - val_loss: 2.0571e-04 - val_mse: 2.0571e-04
Epoch 23/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 2.4816e-04 - mse: 2.4816e-04 - val_loss: 1.2992e-04 - val_mse: 1.2992e-04
Epoch 24/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 2.4286e-04 - mse: 2.4286e-04 - val_loss: 1.4264e-04 - val_mse: 1.4264e-04
Epoch 25/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 2.3842e-04 - mse: 2.3842e-04 - val_loss: 1.0188e-04 - val_mse: 1.0188e-04
Epoch 26/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.3886e-04 - mse: 2.3886e-04 - val_loss: 1.7673e-04 - val_mse: 1.7673e-04
Epoch 27/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.6026e-04 - mse: 2.6026e-04 - val_loss: 1.3870e-04 - val_mse: 1.3870e-04
Epoch 28/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.3586e-04 - mse: 2.3586e-04 - val_loss: 1.1012e-04 - val_mse: 1.1012e-04
Epoch 29/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 2.5916e-04 - mse: 2.5916e-04 - val_loss: 1.0357e-04 - val_mse: 1.0357e-04
Epoch 30/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 2.3070e-04 - mse: 2.3070e-04 - val_loss: 2.3065e-04 - val_mse: 2.3065e-04
Epoch 31/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.3478e-04 - mse: 2.3478e-04 - val_loss: 1.0589e-04 - val_mse: 1.0589e-04
Epoch 32/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2.6309e-04 - mse: 2.6309e-04 - val_loss: 2.3979e-04 - val_mse: 2.3979e-04
Epoch 33/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.2247e-04 - mse: 2.2247e-04 - val_loss: 1.0639e-04 - val_mse: 1.0639e-04
Epoch 34/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 2.2960e-04 - mse: 2.2960e-04 - val_loss: 1.2611e-04 - val_mse: 1.2611e-04
Epoch 35/100000
527/527 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 2.3933e-04 - mse: 2.3933e-04 - val_loss: 2.5885e-04 - val_mse: 2.5885e-04
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.9050e-05 - mse: 9.9050e-05

[9.904980834107846e-05, 9.904980834107846e-05]

In [17]:
y_pred = model.predict(X_test)
r2_score(y_test,y_pred)

65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

0.9474831819534302

In [ ]:
#1.5 ha realizado una predicción para el último trimestre de 2027
df_fila_nueva = df.loc[(df['iso3_code']=='ESP') & (df['year'] == 2026) & (df['industry_sector'] == 'Technology & Software') & (df['quarter'] == 2)]
df_fila_nueva['quarter'] = [4]
df_fila_nueva['year'] = [2027]

C:\Users\Equipo\AppData\Local\Temp\ipykernel_21096\4039567122.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fila_nueva['quarter'] = [4]
C:\Users\Equipo\AppData\Local\Temp\ipykernel_21096\4039567122.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fila_nueva['year'] = [2027]

In [19]:
df_fila_nueva

,iso3_code,region,income_group,year,quarter,industry_sector,sector_automation_risk_score,gdp_per_capita_usd,pct_sector_workforce_displaced
3370,ESP,Europe,High Income,2027,4,Technology & Software,0.366,30362,0.0829

In [20]:
df_con_fila_nueva = pd.concat([df,df_fila_nueva])

In [21]:
df_solucion_con_fila_nueva = df_con_fila_nueva.replace({'High Income':4,'Upper Middle Income':3,'Lower Middle Income':2, 'Low Income':1})

C:\Users\Equipo\AppData\Local\Temp\ipykernel_21096\99603624.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_solucion_con_fila_nueva = df_con_fila_nueva.replace({'High Income':4,'Upper Middle Income':3,'Lower Middle Income':2, 'Low Income':1})

In [22]:
df_solucion_con_fila_nueva = pd.get_dummies(df_solucion_con_fila_nueva,dtype=int)

In [23]:
X_fila = df_solucion_con_fila_nueva.drop(['pct_sector_workforce_displaced'],axis=1)

In [24]:
X_fila = scaler.transform(X_fila)

In [29]:
X_fila.shape

(20801, 107)

In [34]:
model.predict(X_fila[-1:])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

array([[0.11455891]], dtype=float32)

<div style="border-style:groove;border-width:thin;padding:10px">
    <h4>EJERCICIO 2:</h4>
    <p>Descarga y descomprime el archivo 'DeFungi.zip'. Contiene imágenes microscópicas de hongos. Trata de conseguir los siguientes objetivos:</p>
    <ol>
        <li>Carga los datos de las imágenes preparándolos para que sean válidos para entrenar una IA.</li>
        <li>Resuelve el problema con una red neuronal convolucional. Puedes usar todas las técnicas vistas en clase y seguir un proceso correcto para solucionar el problema. Debéis dejar TODAS LAS PRUEBAS QUE HAGÁIS. Debes hacer, al menos, 2 pruebas y explicar que pasa cuando lo haces: coger menos imágenes y reducir la calidad de las imágenes cogiendo todas.</li>
    </ol>
</div>

In [15]:
#2.1 Cargar los datos según los dos métodos propuestos:
#1 A calidad completa pero pocas fotos. 50 de cada. Importante cogerlas por tipos.
photos =  []
labels = []
len_H1 = 0
len_H2 = 0
len_H3 = 0
len_H5 = 0
len_H6 = 0
for file in listdir('DeFungi/'):
    try:    
        if (file[:2] == 'H1') and (len_H1<50):
            photo = load_img('DeFungi/' + file, target_size=(500, 500))
            photos.append(img_to_array(photo))
            id = 0
            len_H1 += 1
            labels.append(float(id))
            del photo
        elif (file[:2] == 'H2') and (len_H2<50):
            photo = load_img('DeFungi/' + file, target_size=(500, 500))
            photos.append(img_to_array(photo))
            id = 1
            len_H2 += 1
            labels.append(float(id))
            del photo
        elif (file[:2] == 'H3') and (len_H3<50):
            photo = load_img('DeFungi/' + file, target_size=(500, 500))
            photos.append(img_to_array(photo))
            id = 2
            len_H3 += 1
            labels.append(float(id))
            del photo
        elif (file[:2] == 'H5') and (len_H5<50):
            photo = load_img('DeFungi/' + file, target_size=(500, 500))
            photos.append(img_to_array(photo))
            id = 3
            len_H5 += 1
            labels.append(float(id))
            del photo
        elif (file[:2] == 'H6') and (len_H6<50):
            photo = load_img('DeFungi/' + file, target_size=(500, 500))
            photos.append(img_to_array(photo))
            id = 4
            len_H6 += 1
            labels.append(float(id))
            del photo
        
    except:
        print('Error en la foto ' + file)

In [16]:
X = asarray(photos)/255.
y = asarray(labels)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [18]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
rnd_clf.fit(X_train.reshape(X_train.shape[0],-1),y_train)
from sklearn.metrics import accuracy_score
y_pred = rnd_clf.predict(X_test.reshape(X_test.shape[0],-1))
print(accuracy_score(y_test,y_pred))

0.52

In [ ]:

#2.2 Diseño de la red convolucional y del entrenamiento.
model = keras.models.Sequential()
model.add(Conv2D(16,(3,3), activation='relu', input_shape = (500,500,3)))
model.add(MaxPool2D(2,2))
model.add(Conv2D(32,(3,3), activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(256,(3,3), activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Flatten())
#Haciendo summary se ve que de la flatten salen 215000 salidas. Como es imposible poner 140000 neuronas, pongo muchas pero menos.
model.add(keras.layers.Dense(2048,activation='relu',kernel_initializer='he_normal'))
model.add(keras.layers.Dense(512,activation='relu',kernel_initializer='he_normal'))
model.add(keras.layers.Dense(5,activation='softmax',kernel_initializer='glorot_normal'))

c:\Users\Equipo\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer = keras.optimizers.Adam(learning_rate=0.0001, beta_1=0.9, beta_2=0.999), metrics=['accuracy'])
early_stopping_cb = keras.callbacks.EarlyStopping(patience=5,
restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=2,validation_split = 0.1,callbacks=[early_stopping_cb],batch_size=256)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/2
1/1 ━━━━━━━━━━━━━━━━━━━━ 15s 15s/step - accuracy: 0.2327 - loss: 1.6080 - val_accuracy: 0.2174 - val_loss: 1.6087
Epoch 2/2
1/1 ━━━━━━━━━━━━━━━━━━━━ 12s 12s/step - accuracy: 0.1980 - loss: 1.5998 - val_accuracy: 0.2174 - val_loss: 1.6470

In [10]:
model.evaluate(X_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - accuracy: 0.2000 - loss: 1.6343

[1.6342763900756836, 0.20000000298023224]

In [ ]:
#2.1 bajando calidad. En este caso no hace falta bajar muchísimo.
photos =  []
labels = []
len_H1 = 0
len_H2 = 0
len_H3 = 0
len_H5 = 0
len_H6 = 0
for file in listdir('DeFungi/'):
    try:    
        if (file[:2] == 'H1') and (len_H1<300):
            photo = load_img('DeFungi/' + file, target_size=(100, 100))
            photos.append(img_to_array(photo))
            id = 0
            len_H1 += 1
            labels.append(float(id))
            del photo
        elif (file[:2] == 'H2') and (len_H2<300):
            photo = load_img('DeFungi/' + file, target_size=(100, 100))
            photos.append(img_to_array(photo))
            id = 1
            len_H2 += 1
            labels.append(float(id))
            del photo
        elif (file[:2] == 'H3') and (len_H3<300):
            photo = load_img('DeFungi/' + file, target_size=(100, 100))
            photos.append(img_to_array(photo))
            id = 2
            len_H3 += 1
            labels.append(float(id))
            del photo
        elif (file[:2] == 'H5') and (len_H5<300):
            photo = load_img('DeFungi/' + file, target_size=(100, 100))
            photos.append(img_to_array(photo))
            id = 3
            len_H5 += 1
            labels.append(float(id))
            del photo
        elif (file[:2] == 'H6') and (len_H6<300):
            photo = load_img('DeFungi/' + file, target_size=(100, 100))
            photos.append(img_to_array(photo))
            id = 4
            len_H6 += 1
            labels.append(float(id))
            del photo
        
    except:
        print('Error en la foto ' + file)

In [33]:
X = asarray(photos)/255.
y = asarray(labels)

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [35]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
rnd_clf.fit(X_train.reshape(X_train.shape[0],-1),y_train)
from sklearn.metrics import accuracy_score
y_pred = rnd_clf.predict(X_test.reshape(X_test.shape[0],-1))
print(accuracy_score(y_test,y_pred))

0.5666666666666667

In [36]:

model = keras.models.Sequential()
model.add(Conv2D(16,(3,3), activation='relu', input_shape = (100,100,3)))
model.add(MaxPool2D(2,2))
model.add(Conv2D(32,(3,3), activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(256,(3,3), activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Flatten())
model.add(keras.layers.Dense(256,activation='relu',kernel_initializer='he_normal'))
model.add(keras.layers.Dense(64,activation='relu',kernel_initializer='he_normal'))
model.add(keras.layers.Dense(5,activation='softmax',kernel_initializer='glorot_normal'))

c:\Users\Equipo\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 498, 498, 16)   │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 249, 249, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 247, 247, 32)   │         4,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 123, 123, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 121, 121, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 60, 60, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 58, 58, 256)    │       147,712 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 29, 29, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 215296)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 100)            │    21,529,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 20)             │         2,020 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │           105 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,703,121 (82.79 MB)

 Trainable params: 21,703,121 (82.79 MB)

 Non-trainable params: 0 (0.00 B)

In [37]:
#Usamos Nadam. Se podrían usar otros optimizadores, pero el resultado es similar.
model.compile(loss='sparse_categorical_crossentropy', optimizer = keras.optimizers.Adam(learning_rate=0.0001, beta_1=0.9, beta_2=0.999), metrics=['accuracy'])
early_stopping_cb = keras.callbacks.EarlyStopping(patience=10,
restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=1000,validation_split = 0.1,callbacks=[early_stopping_cb],batch_size=256)

Epoch 1/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 4s 409ms/step - accuracy: 0.2395 - loss: 1.6071 - val_accuracy: 0.2815 - val_loss: 1.5989
Epoch 2/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 372ms/step - accuracy: 0.3391 - loss: 1.5937 - val_accuracy: 0.3926 - val_loss: 1.5861
Epoch 3/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 363ms/step - accuracy: 0.3934 - loss: 1.5773 - val_accuracy: 0.3556 - val_loss: 1.5666
Epoch 4/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 357ms/step - accuracy: 0.3753 - loss: 1.5547 - val_accuracy: 0.3630 - val_loss: 1.5418
Epoch 5/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 326ms/step - accuracy: 0.3877 - loss: 1.5247 - val_accuracy: 0.3852 - val_loss: 1.5081
Epoch 6/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 323ms/step - accuracy: 0.3967 - loss: 1.4828 - val_accuracy: 0.3926 - val_loss: 1.4675
Epoch 7/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 321ms/step - accuracy: 0.4107 - loss: 1.4323 - val_accuracy: 0.4963 - val_loss: 1.4294
Epoch 8/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 356ms/step - accuracy: 0.4979 - loss: 1.3827 - val_accuracy: 0.5037 - val_loss: 1.3908
Epoch 9/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 377ms/step - accuracy: 0.5078 - loss: 1.3460 - val_accuracy: 0.4889 - val_loss: 1.3658
Epoch 10/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 359ms/step - accuracy: 0.5103 - loss: 1.3165 - val_accuracy: 0.5111 - val_loss: 1.3420
Epoch 11/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 357ms/step - accuracy: 0.5078 - loss: 1.2935 - val_accuracy: 0.5037 - val_loss: 1.3331
Epoch 12/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 363ms/step - accuracy: 0.4979 - loss: 1.2755 - val_accuracy: 0.4889 - val_loss: 1.2992
Epoch 13/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 357ms/step - accuracy: 0.5095 - loss: 1.2577 - val_accuracy: 0.4519 - val_loss: 1.3053
Epoch 14/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 366ms/step - accuracy: 0.4889 - loss: 1.2558 - val_accuracy: 0.4889 - val_loss: 1.2700
Epoch 15/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 333ms/step - accuracy: 0.5037 - loss: 1.2392 - val_accuracy: 0.5185 - val_loss: 1.2556
Epoch 16/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 339ms/step - accuracy: 0.5309 - loss: 1.2225 - val_accuracy: 0.4889 - val_loss: 1.2554
Epoch 17/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 329ms/step - accuracy: 0.5226 - loss: 1.2184 - val_accuracy: 0.5037 - val_loss: 1.2376
Epoch 18/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 339ms/step - accuracy: 0.5086 - loss: 1.2183 - val_accuracy: 0.5111 - val_loss: 1.2373
Epoch 19/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 338ms/step - accuracy: 0.5218 - loss: 1.2058 - val_accuracy: 0.5037 - val_loss: 1.2343
Epoch 20/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 333ms/step - accuracy: 0.5235 - loss: 1.1967 - val_accuracy: 0.4963 - val_loss: 1.2380
Epoch 21/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 338ms/step - accuracy: 0.5029 - loss: 1.1988 - val_accuracy: 0.4963 - val_loss: 1.2112
Epoch 22/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 332ms/step - accuracy: 0.5111 - loss: 1.1936 - val_accuracy: 0.5259 - val_loss: 1.2161
Epoch 23/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 329ms/step - accuracy: 0.5226 - loss: 1.1855 - val_accuracy: 0.5333 - val_loss: 1.1962
Epoch 24/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 331ms/step - accuracy: 0.5119 - loss: 1.1747 - val_accuracy: 0.4889 - val_loss: 1.2108
Epoch 25/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 340ms/step - accuracy: 0.5235 - loss: 1.1702 - val_accuracy: 0.5185 - val_loss: 1.1937
Epoch 26/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 346ms/step - accuracy: 0.5325 - loss: 1.1573 - val_accuracy: 0.4963 - val_loss: 1.1817
Epoch 27/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 347ms/step - accuracy: 0.5292 - loss: 1.1484 - val_accuracy: 0.5037 - val_loss: 1.1812
Epoch 28/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 337ms/step - accuracy: 0.5358 - loss: 1.1398 - val_accuracy: 0.5037 - val_loss: 1.1635
Epoch 29/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 340ms/step - accuracy: 0.5391 - loss: 1.1402 - val_accuracy: 0.5037 - val_loss: 1.1587
Epoch 30/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 343ms/step - accuracy: 0.5399 - loss: 1.1304 - val_accuracy: 0.4815 - val_loss: 1.1571
Epoch 31/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 345ms/step - accuracy: 0.5300 - loss: 1.1214 - val_accuracy: 0.5407 - val_loss: 1.1393
Epoch 32/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 341ms/step - accuracy: 0.5457 - loss: 1.1113 - val_accuracy: 0.5037 - val_loss: 1.1413
Epoch 33/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 343ms/step - accuracy: 0.5539 - loss: 1.1062 - val_accuracy: 0.5407 - val_loss: 1.1414
Epoch 34/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 337ms/step - accuracy: 0.5325 - loss: 1.1011 - val_accuracy: 0.5407 - val_loss: 1.1187
Epoch 35/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 342ms/step - accuracy: 0.5407 - loss: 1.0956 - val_accuracy: 0.4889 - val_loss: 1.1157
Epoch 36/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 337ms/step - accuracy: 0.5481 - loss: 1.0891 - val_accuracy: 0.5333 - val_loss: 1.1280
Epoch 37/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 355ms/step - accuracy: 0.5432 - loss: 1.0971 - val_accuracy: 0.5111 - val_loss: 1.1048
Epoch 38/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 340ms/step - accuracy: 0.5523 - loss: 1.0844 - val_accuracy: 0.5037 - val_loss: 1.1137
Epoch 39/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 334ms/step - accuracy: 0.5383 - loss: 1.0855 - val_accuracy: 0.5556 - val_loss: 1.0959
Epoch 40/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 339ms/step - accuracy: 0.5621 - loss: 1.0658 - val_accuracy: 0.5037 - val_loss: 1.0885
Epoch 41/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 334ms/step - accuracy: 0.5523 - loss: 1.0569 - val_accuracy: 0.5407 - val_loss: 1.0872
Epoch 42/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 330ms/step - accuracy: 0.5580 - loss: 1.0494 - val_accuracy: 0.5185 - val_loss: 1.0737
Epoch 43/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 336ms/step - accuracy: 0.5671 - loss: 1.0417 - val_accuracy: 0.5259 - val_loss: 1.0723
Epoch 44/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 331ms/step - accuracy: 0.5712 - loss: 1.0349 - val_accuracy: 0.5556 - val_loss: 1.0734
Epoch 45/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 329ms/step - accuracy: 0.5621 - loss: 1.0335 - val_accuracy: 0.5407 - val_loss: 1.0615
Epoch 46/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 340ms/step - accuracy: 0.5737 - loss: 1.0250 - val_accuracy: 0.5481 - val_loss: 1.0544
Epoch 47/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 332ms/step - accuracy: 0.5737 - loss: 1.0201 - val_accuracy: 0.5556 - val_loss: 1.0561
Epoch 48/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 328ms/step - accuracy: 0.5852 - loss: 1.0087 - val_accuracy: 0.5556 - val_loss: 1.0425
Epoch 49/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 336ms/step - accuracy: 0.5901 - loss: 1.0071 - val_accuracy: 0.5630 - val_loss: 1.0386
Epoch 50/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 334ms/step - accuracy: 0.5934 - loss: 0.9981 - val_accuracy: 0.6000 - val_loss: 1.0285
Epoch 51/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 333ms/step - accuracy: 0.5885 - loss: 0.9953 - val_accuracy: 0.6000 - val_loss: 1.0352
Epoch 52/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 336ms/step - accuracy: 0.6058 - loss: 0.9863 - val_accuracy: 0.5852 - val_loss: 1.0314
Epoch 53/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 329ms/step - accuracy: 0.6033 - loss: 0.9867 - val_accuracy: 0.6000 - val_loss: 1.0310
Epoch 54/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 349ms/step - accuracy: 0.6008 - loss: 0.9838 - val_accuracy: 0.5185 - val_loss: 1.0317
Epoch 55/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 331ms/step - accuracy: 0.6016 - loss: 0.9842 - val_accuracy: 0.6074 - val_loss: 1.0155
Epoch 56/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 330ms/step - accuracy: 0.5934 - loss: 0.9701 - val_accuracy: 0.6148 - val_loss: 1.0045
Epoch 57/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 333ms/step - accuracy: 0.5967 - loss: 0.9675 - val_accuracy: 0.5778 - val_loss: 1.0261
Epoch 58/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 331ms/step - accuracy: 0.6222 - loss: 0.9520 - val_accuracy: 0.6222 - val_loss: 1.0027
Epoch 59/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 333ms/step - accuracy: 0.6189 - loss: 0.9459 - val_accuracy: 0.5333 - val_loss: 1.0017
Epoch 60/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 337ms/step - accuracy: 0.6082 - loss: 0.9490 - val_accuracy: 0.6074 - val_loss: 1.0136
Epoch 61/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 331ms/step - accuracy: 0.6074 - loss: 0.9383 - val_accuracy: 0.5778 - val_loss: 0.9924
Epoch 62/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 344ms/step - accuracy: 0.5942 - loss: 0.9378 - val_accuracy: 0.6000 - val_loss: 0.9891
Epoch 63/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 335ms/step - accuracy: 0.6173 - loss: 0.9287 - val_accuracy: 0.6000 - val_loss: 0.9876
Epoch 64/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 335ms/step - accuracy: 0.6280 - loss: 0.9212 - val_accuracy: 0.6222 - val_loss: 0.9713
Epoch 65/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 338ms/step - accuracy: 0.6198 - loss: 0.9100 - val_accuracy: 0.5926 - val_loss: 0.9671
Epoch 66/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 335ms/step - accuracy: 0.6156 - loss: 0.9180 - val_accuracy: 0.6148 - val_loss: 0.9783
Epoch 67/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 333ms/step - accuracy: 0.6239 - loss: 0.9117 - val_accuracy: 0.5926 - val_loss: 0.9670
Epoch 68/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 336ms/step - accuracy: 0.6329 - loss: 0.9016 - val_accuracy: 0.6296 - val_loss: 0.9579
Epoch 69/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 332ms/step - accuracy: 0.6313 - loss: 0.9107 - val_accuracy: 0.6222 - val_loss: 0.9584
Epoch 70/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 329ms/step - accuracy: 0.6247 - loss: 0.9003 - val_accuracy: 0.6222 - val_loss: 0.9412
Epoch 71/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 347ms/step - accuracy: 0.6370 - loss: 0.8854 - val_accuracy: 0.6148 - val_loss: 0.9447
Epoch 72/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 332ms/step - accuracy: 0.6469 - loss: 0.8861 - val_accuracy: 0.6296 - val_loss: 0.9315
Epoch 73/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 328ms/step - accuracy: 0.6477 - loss: 0.8776 - val_accuracy: 0.6370 - val_loss: 0.9220
Epoch 74/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 338ms/step - accuracy: 0.6519 - loss: 0.8751 - val_accuracy: 0.6444 - val_loss: 0.9202
Epoch 75/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 337ms/step - accuracy: 0.6453 - loss: 0.8793 - val_accuracy: 0.6370 - val_loss: 0.9298
Epoch 76/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 333ms/step - accuracy: 0.6486 - loss: 0.8681 - val_accuracy: 0.6444 - val_loss: 0.9014
Epoch 77/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 329ms/step - accuracy: 0.6510 - loss: 0.8603 - val_accuracy: 0.6370 - val_loss: 0.9173
Epoch 78/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 340ms/step - accuracy: 0.6494 - loss: 0.8641 - val_accuracy: 0.6519 - val_loss: 0.9008
Epoch 79/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 354ms/step - accuracy: 0.6560 - loss: 0.8571 - val_accuracy: 0.6444 - val_loss: 0.8958
Epoch 80/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 334ms/step - accuracy: 0.6560 - loss: 0.8481 - val_accuracy: 0.6074 - val_loss: 0.9115
Epoch 81/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 335ms/step - accuracy: 0.6658 - loss: 0.8480 - val_accuracy: 0.6519 - val_loss: 0.8821
Epoch 82/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 335ms/step - accuracy: 0.6683 - loss: 0.8444 - val_accuracy: 0.6667 - val_loss: 0.8757
Epoch 83/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 331ms/step - accuracy: 0.6650 - loss: 0.8393 - val_accuracy: 0.6667 - val_loss: 0.8835
Epoch 84/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 345ms/step - accuracy: 0.6675 - loss: 0.8348 - val_accuracy: 0.6667 - val_loss: 0.8690
Epoch 85/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 336ms/step - accuracy: 0.6691 - loss: 0.8316 - val_accuracy: 0.6963 - val_loss: 0.8556
Epoch 86/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 334ms/step - accuracy: 0.6807 - loss: 0.8224 - val_accuracy: 0.6963 - val_loss: 0.8750
Epoch 87/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 332ms/step - accuracy: 0.6757 - loss: 0.8234 - val_accuracy: 0.6815 - val_loss: 0.8539
Epoch 88/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 331ms/step - accuracy: 0.6667 - loss: 0.8215 - val_accuracy: 0.7111 - val_loss: 0.8396
Epoch 89/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 337ms/step - accuracy: 0.6700 - loss: 0.8191 - val_accuracy: 0.6741 - val_loss: 0.8663
Epoch 90/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 336ms/step - accuracy: 0.6675 - loss: 0.8162 - val_accuracy: 0.6444 - val_loss: 0.8894
Epoch 91/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 345ms/step - accuracy: 0.6716 - loss: 0.8169 - val_accuracy: 0.7037 - val_loss: 0.8286
Epoch 92/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 373ms/step - accuracy: 0.6716 - loss: 0.8084 - val_accuracy: 0.7037 - val_loss: 0.8242
Epoch 93/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 396ms/step - accuracy: 0.6765 - loss: 0.8054 - val_accuracy: 0.6741 - val_loss: 0.8441
Epoch 94/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 392ms/step - accuracy: 0.6790 - loss: 0.8083 - val_accuracy: 0.6889 - val_loss: 0.8333
Epoch 95/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 410ms/step - accuracy: 0.6815 - loss: 0.8016 - val_accuracy: 0.6741 - val_loss: 0.8246
Epoch 96/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 449ms/step - accuracy: 0.6889 - loss: 0.7915 - val_accuracy: 0.6889 - val_loss: 0.8346
Epoch 97/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 540ms/step - accuracy: 0.6741 - loss: 0.7988 - val_accuracy: 0.6889 - val_loss: 0.8160
Epoch 98/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 420ms/step - accuracy: 0.6872 - loss: 0.7840 - val_accuracy: 0.6963 - val_loss: 0.8114
Epoch 99/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 632ms/step - accuracy: 0.6897 - loss: 0.7781 - val_accuracy: 0.6667 - val_loss: 0.8273
Epoch 100/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 459ms/step - accuracy: 0.6840 - loss: 0.7897 - val_accuracy: 0.6296 - val_loss: 0.9024
Epoch 101/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 574ms/step - accuracy: 0.6642 - loss: 0.8065 - val_accuracy: 0.6741 - val_loss: 0.8080
Epoch 102/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 721ms/step - accuracy: 0.6741 - loss: 0.7906 - val_accuracy: 0.6963 - val_loss: 0.8046
Epoch 103/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 5s 939ms/step - accuracy: 0.6889 - loss: 0.7781 - val_accuracy: 0.7185 - val_loss: 0.8044
Epoch 104/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 6s 1s/step - accuracy: 0.6798 - loss: 0.7849 - val_accuracy: 0.6815 - val_loss: 0.8501
Epoch 105/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 5s 925ms/step - accuracy: 0.6757 - loss: 0.7853 - val_accuracy: 0.6815 - val_loss: 0.8241
Epoch 106/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 537ms/step - accuracy: 0.6856 - loss: 0.7769 - val_accuracy: 0.6963 - val_loss: 0.7814
Epoch 107/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 547ms/step - accuracy: 0.6922 - loss: 0.7609 - val_accuracy: 0.6963 - val_loss: 0.7933
Epoch 108/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 570ms/step - accuracy: 0.6807 - loss: 0.7787 - val_accuracy: 0.6667 - val_loss: 0.8445
Epoch 109/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 4s 738ms/step - accuracy: 0.6733 - loss: 0.7798 - val_accuracy: 0.6593 - val_loss: 0.7963
Epoch 110/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 581ms/step - accuracy: 0.6922 - loss: 0.7712 - val_accuracy: 0.7333 - val_loss: 0.7754
Epoch 111/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 5s 522ms/step - accuracy: 0.6955 - loss: 0.7514 - val_accuracy: 0.7333 - val_loss: 0.7516
Epoch 112/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 517ms/step - accuracy: 0.7053 - loss: 0.7401 - val_accuracy: 0.6741 - val_loss: 0.7974
Epoch 113/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 541ms/step - accuracy: 0.6996 - loss: 0.7409 - val_accuracy: 0.7481 - val_loss: 0.7591
Epoch 114/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 507ms/step - accuracy: 0.7029 - loss: 0.7383 - val_accuracy: 0.7481 - val_loss: 0.7553
Epoch 115/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 489ms/step - accuracy: 0.7021 - loss: 0.7384 - val_accuracy: 0.6741 - val_loss: 0.8037
Epoch 116/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 489ms/step - accuracy: 0.6971 - loss: 0.7362 - val_accuracy: 0.7037 - val_loss: 0.7522
Epoch 117/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 523ms/step - accuracy: 0.7029 - loss: 0.7325 - val_accuracy: 0.7333 - val_loss: 0.7534
Epoch 118/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 506ms/step - accuracy: 0.7103 - loss: 0.7250 - val_accuracy: 0.7333 - val_loss: 0.7374
Epoch 119/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 487ms/step - accuracy: 0.7103 - loss: 0.7197 - val_accuracy: 0.7481 - val_loss: 0.7351
Epoch 120/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 500ms/step - accuracy: 0.7169 - loss: 0.7214 - val_accuracy: 0.6815 - val_loss: 0.7846
Epoch 121/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 509ms/step - accuracy: 0.7111 - loss: 0.7242 - val_accuracy: 0.7556 - val_loss: 0.7389
Epoch 122/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 511ms/step - accuracy: 0.7062 - loss: 0.7231 - val_accuracy: 0.7556 - val_loss: 0.7276
Epoch 123/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 504ms/step - accuracy: 0.7243 - loss: 0.7122 - val_accuracy: 0.7037 - val_loss: 0.7629
Epoch 124/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 501ms/step - accuracy: 0.7136 - loss: 0.7162 - val_accuracy: 0.7259 - val_loss: 0.7258
Epoch 125/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 360ms/step - accuracy: 0.7111 - loss: 0.7103 - val_accuracy: 0.7481 - val_loss: 0.7281
Epoch 126/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 375ms/step - accuracy: 0.7086 - loss: 0.7155 - val_accuracy: 0.7037 - val_loss: 0.7480
Epoch 127/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 345ms/step - accuracy: 0.6963 - loss: 0.7167 - val_accuracy: 0.6815 - val_loss: 0.7722
Epoch 128/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 352ms/step - accuracy: 0.7037 - loss: 0.7162 - val_accuracy: 0.7111 - val_loss: 0.7198
Epoch 129/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 350ms/step - accuracy: 0.7095 - loss: 0.6968 - val_accuracy: 0.7111 - val_loss: 0.7181
Epoch 130/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 346ms/step - accuracy: 0.7210 - loss: 0.6985 - val_accuracy: 0.7333 - val_loss: 0.7311
Epoch 131/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 372ms/step - accuracy: 0.7070 - loss: 0.6962 - val_accuracy: 0.7704 - val_loss: 0.6986
Epoch 132/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 359ms/step - accuracy: 0.7169 - loss: 0.6914 - val_accuracy: 0.7407 - val_loss: 0.7219
Epoch 133/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 479ms/step - accuracy: 0.7243 - loss: 0.6821 - val_accuracy: 0.7556 - val_loss: 0.6998
Epoch 134/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 427ms/step - accuracy: 0.7185 - loss: 0.6806 - val_accuracy: 0.7704 - val_loss: 0.6986
Epoch 135/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 448ms/step - accuracy: 0.7267 - loss: 0.6777 - val_accuracy: 0.7259 - val_loss: 0.7113
Epoch 136/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 432ms/step - accuracy: 0.7210 - loss: 0.6829 - val_accuracy: 0.7407 - val_loss: 0.7112
Epoch 137/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 384ms/step - accuracy: 0.7152 - loss: 0.6776 - val_accuracy: 0.7704 - val_loss: 0.6998
Epoch 138/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 380ms/step - accuracy: 0.7292 - loss: 0.6769 - val_accuracy: 0.7037 - val_loss: 0.7184
Epoch 139/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 423ms/step - accuracy: 0.7276 - loss: 0.6804 - val_accuracy: 0.7778 - val_loss: 0.6859
Epoch 140/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 624ms/step - accuracy: 0.7259 - loss: 0.6752 - val_accuracy: 0.7630 - val_loss: 0.7021
Epoch 141/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 503ms/step - accuracy: 0.7276 - loss: 0.6767 - val_accuracy: 0.7630 - val_loss: 0.6879
Epoch 142/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 489ms/step - accuracy: 0.7259 - loss: 0.6658 - val_accuracy: 0.7037 - val_loss: 0.7235
Epoch 143/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 557ms/step - accuracy: 0.7235 - loss: 0.6807 - val_accuracy: 0.7407 - val_loss: 0.7034
Epoch 144/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 501ms/step - accuracy: 0.7160 - loss: 0.6898 - val_accuracy: 0.6963 - val_loss: 0.7421
Epoch 145/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 494ms/step - accuracy: 0.7226 - loss: 0.6987 - val_accuracy: 0.7037 - val_loss: 0.7249
Epoch 146/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 495ms/step - accuracy: 0.7202 - loss: 0.6871 - val_accuracy: 0.7704 - val_loss: 0.7007
Epoch 147/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 480ms/step - accuracy: 0.7440 - loss: 0.6768 - val_accuracy: 0.7333 - val_loss: 0.7041
Epoch 148/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 496ms/step - accuracy: 0.7317 - loss: 0.6648 - val_accuracy: 0.7778 - val_loss: 0.6728
Epoch 149/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 489ms/step - accuracy: 0.7284 - loss: 0.6686 - val_accuracy: 0.7259 - val_loss: 0.6984
Epoch 150/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 495ms/step - accuracy: 0.7424 - loss: 0.6601 - val_accuracy: 0.7852 - val_loss: 0.6730
Epoch 151/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 484ms/step - accuracy: 0.7490 - loss: 0.6481 - val_accuracy: 0.7704 - val_loss: 0.6687
Epoch 152/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 497ms/step - accuracy: 0.7432 - loss: 0.6457 - val_accuracy: 0.8000 - val_loss: 0.6760
Epoch 153/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 490ms/step - accuracy: 0.7572 - loss: 0.6409 - val_accuracy: 0.7778 - val_loss: 0.6608
Epoch 154/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 623ms/step - accuracy: 0.7523 - loss: 0.6450 - val_accuracy: 0.7926 - val_loss: 0.6590
Epoch 155/1000

In [38]:
model.evaluate(X_test,y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7133 - loss: 0.6896

[0.6896077394485474, 0.7133333086967468]